### PR TITLE
Only one share per task is sent if mining is turned off

### PR DESCRIPTION
**Pull request by jonano614**

### CODE REVIEW

**Comment by jonano614** [comment]
Yes, from response.

**Comment by xrdavies** [comment]
If balance of wallet is fetched through share, if not share send to pool, the balance of wallet is not updated locally. So the receiver will have to wait for a long time to see the result of TX.

**Comment by jonano614** [comment]
Nope, pool balance if not fetched through share. Share is a data for sending, balance and new task - is a data for receiving.

**Comment by xrdavies** [comment]
@jonano614 Please check the function send_data_to_connection, it sends balance for wallet.

**Comment by jonano614** [comment]
Fixed.

**Pull request merged**
