### PR TITLE
add thread to send new blocks

### PR DESCRIPTION
**Pull request by xrdavies**
* add thread to send new blocks
* add hidden command to disable auto refresh for pool owners.

### CODE REVIEW

**Comment by xrdavies** [comment]
@sgaragagghu 
With thousands of miners, it will be not just millisecond, it will depends on ethernet card, previous implementation just call write which will wait until the end peer receive the data in buffer area. 
To send new blocks in separate thread is to prevent blocking current thread for next payment in which case the pool will skip next payment if blocked for over 64 seconds.
I cannot answer you about how long it will take to do payment. It will depends on network and how many blocks need to be sent. But with this implementation it will not block next payment.

But thanks for comments on mutex, it blocks the thread.

**Comment by xrdavies** [comment]
@sgaragagghu  Updated.

**Comment by sgaragagghu** [comment]
Maybe you could tell to the send_thread to clean the list and control this process with some shared variables, instead of another function(reset funciton) that want to join critical section.

**Comment by xrdavies** [comment]
@sgaragagghu Free blocks is done by reset_callback. Split things into different functions, not mess them together to keep it as simple as possible.  Last update to modify mutex causes some issue with memory. I will fix it later.

**Comment by xrdavies** [comment]
@sgaragagghu  Could you specify what errors you saw in pool.c?

**Comment by sgaragagghu** [comment]
Hypothesis: the thread doesn't finish before the new main block, so you can simply fix it in this way:

`	for(;;) {
		int processed = 0;
		const uint64_t task_index = g_xdag_pool_task_index;
		struct xdag_pool_task *task = &g_xdag_pool_task[task_index & 1];
		const xdag_time_t current_task_time = task->task_time;

		if(current_task_time > prev_task_time) {
			uint64_t *hash = g_xdag_mined_hashes[(current_task_time - CONFIRMATIONS_COUNT + 1) & (CONFIRMATIONS_COUNT - 1)];

			processed = 1;
			prev_task_time = current_task_time;

			res = pay_miners(current_task_time - CONFIRMATIONS_COUNT + 1);
			remove_inactive_miners();

			xdag_info("%s: %016llx%016llx%016llx%016llx t=%llx res=%d", (res ? "Nopaid" : "Paid  "),
				hash[3], hash[2], hash[1], hash[0], (current_task_time - CONFIRMATIONS_COUNT + 1) << 16 | 0xffff, res);
		}
`

The issue is that you just have current_task_time and prev_task_time, you need to remember N (maybe N=CONFIRMATIONS_COUNT) last_task_timeS. Do you need that: this --> g_xdag_pool_task_index became an array (or, easily, a FIFO list, with head, for example, *g_xdag_pool_task_indexes)
So when g_xdag_pool_task_index is modified (in block.c, create_block), add the new index in the list (as last).

Now, here

`for(;;) {
		int processed = 0;
		const uint64_t task_index = g_xdag_pool_task_index;
		struct xdag_pool_task *task = &g_xdag_pool_task[task_index & 1];
		const xdag_time_t current_task_time = task->task_time;

		if(current_task_time > prev_task_time) {
		[............]
		}
}`

change it with something like:


`for(;;) {
		int processed = 0;
		uint64_t task_index = g_xdag_pool_task_index;
		struct xdag_pool_task *task = &g_xdag_pool_task[task_index & 1];
		xdag_time_t current_task_time = task->task_time;

		if (current_task_time > prev_task_time) {
				uint64_t task_index_tmp = pop(g_xdag_pool_task_indexes);
				struct xdag_pool_task *task_tmp = &g_xdag_pool_task[task_index_tmp & 1];
 				xdag_time_t current_task_time_tmp = task_tmp->task_time;
				if (current_task_time_tmp > prev_task_time){
					current_task_time = current_task_time_tmp;
				}
		[............]
		}
}`

And it will pay for every task...

OR, Another easiest way without the list:
`for(;;) {
		int processed = 0;
		uint64_t task_index = g_xdag_pool_task_index;
		struct xdag_pool_task *task = &g_xdag_pool_task[task_index & 1];
		xdag_time_t current_task_time = task->task_time;

		if (current_task_time > prev_task_time) {
				uint64_t task_index_tmp = search_the_task_index_with_this_task_time(prev_task_time);
				struct xdag_pool_task *task_tmp = &g_xdag_pool_task[(task_index_tmp+1) & 1];
 				xdag_time_t current_task_time_tmp = task_tmp->task_time;
				if (current_task_time_tmp > prev_task_time){
					current_task_time = current_task_time_tmp;
				}
		[............]
		}
}`

`uint64_t task_index_tmp = search_the_task_index_with_this_task_time(prev_task_time);`
this function just need to "traverse" all task (that are CONFIRMATION_COUNT-1 ) to search the one with the prev_task_time, if you traverse the task starting from g_xdag_pool_task_index and going back, you should find it in just 1 iteration (and you need to add a mutex for this array)

So if you think that this is the issue, you can fix it in few minutes.

**Comment by sgaragagghu** [comment]
Only read the end, this is the best way to do it easily

**Comment by jonano614** [comment]
@xrdavies, I understand every developer might have own point of view how to resolve some issue. 
My idea was to reuse existing queue of blocks for sending, not creating a new one. 
I need to think.

**Comment by jonano614** [comment]
Great!

**Comment by sgaragagghu** [comment]
Hotfixed since it was on master
#313

**Pull request merged**
