### PR TITLE
load dnet_keys.bin for mac

### PR DESCRIPTION
**Pull request by xrdavies**
* load dnet_keys.bin for mac

@jonano614 Please help to check it on Windows.

### CODE REVIEW

**Comment by xrdavies** [comment]
```The file dnet_keys.bin is already in the repository, it does not need to be generated every time. In Linux, this file is included in the program using assembler code:

asm (
".text \ n"
"g_xkeys: \ n"
".incbin" ../dnet/dnet_keys.bin "\ n"
);

I think the same can be done in other systems (Windows, MAC), but how - I do not know.

As for the algorithm for generating this file, it can be:

as its first half (g_xkeys.priv and g_xkeys.pub), you can take any file dnet_key.dat generated when xdag is first started with an empty password;
memcpy (& g_xkeys.priv, & another_dnet_key.priv, sizeof (struct dnet_key));
memcpy (& g_xkeys.pub, & another_dnet_key.pub, sizeof (struct dnet_key));

the last part (g_xkeys.sect0) can be generated by the function dnet_random_sector;
dnet_random_sector (g_xkeys.sect0.word);

The middle part (g_xkeys.sect0_encoded) can be obtained as follows:
memcpy (g_xkeys.sect0_encoded.word, g_xkeys.sect0.word, SECTOR_SIZE);
dfsrsa_crypt (g_xkeys.sect0_encoded.word, SECTOR_SIZE / sizeof (dfsrsa_t), & g_xkeys.priv, DNET_KEYLEN);

But the generation process takes time, so a pre-generated file is inserted into the program.```

**Comment by xrdavies** [comment]
> The file dnet_keys.bin is already in the repository, it does not need to be generated every time. In Linux, this file is included in the program using assembler code:
> asm (
> ".text \ n"
> "g_xkeys: \ n"
> ".incbin" ../dnet/dnet_keys.bin "\ n"
> );
> 
> I think the same can be done in other systems (Windows, MAC), but how - I do not know.
> 
> As for the algorithm for generating this file, it can be:
> 
> as its first half (g_xkeys.priv and g_xkeys.pub), you can take any file dnet_key.dat generated when xdag is first started with an empty password;
> memcpy (& g_xkeys.priv, & another_dnet_key.priv, sizeof (struct dnet_key));
> memcpy (& g_xkeys.pub, & another_dnet_key.pub, sizeof (struct dnet_key));
> 
> the last part (g_xkeys.sect0) can be generated by the function dnet_random_sector;
> dnet_random_sector (g_xkeys.sect0.word);
> 
> The middle part (g_xkeys.sect0_encoded) can be obtained as follows:
> memcpy (g_xkeys.sect0_encoded.word, g_xkeys.sect0.word, SECTOR_SIZE);
> dfsrsa_crypt (g_xkeys.sect0_encoded.word, SECTOR_SIZE / sizeof (dfsrsa_t), & g_xkeys.priv, DNET_KEYLEN);
> 
> But the generation process takes time, so a pre-generated file is inserted into the program.```

**Comment by 0xda9** [comment]
Файл dnet_keys.bin нужен только полным нодам. В клиентах (кошельках, майнерах) его можно не грузить. Поэтому загрузку можно внести под условие if (nthreads >= 1) { ... }

**Comment by xrdavies** [comment]
@0xda9  Thanks for feedback.

**Comment by xrdavies** [comment]
@0xda9 My discord account is frozen#0085. Could you PM me? I have something to discuss with you about BlockChain Conf in South Korea.

**Comment by 0xda9** [comment]
0xda9#6163

**Pull request merged**
