### PR TITLE
handle reserved type fields for forward compatibility

### PR DESCRIPTION
**Pull request by xrdavies**
handle reserved type fields for forward compatibility

### CODE REVIEW

**Comment by sgaragagghu** [comment]
Type has 64bit, why there could be only 16 types?

**Comment by xrdavies** [comment]
@sgaragagghu 
```struct xdag_field {
	union {
		struct {
			union {
				struct {
					uint64_t transport_header;
					uint64_t type;
					xdag_time_t time;
				};
				xdag_hashlow_t hash;
			};
			union {
				xdag_amount_t amount;
				xdag_time_t end_time;
			};
		};
		xdag_hash_t data;
	};
};
```


the filed type in xdag_field has 64bits, and only the header xdag field represents the types of the fields in one block. Each 4 bits represent the type of one xdag field in block, each block has 16 xdag fields, so the `type` field in header have to represent 16 xdag field.

For example
64bits is 0xf f f f f f f f f f f f f f f f, `0xf` means 4 bits.
The first `f` means the type of the first xdag field. The second `f` means the type of the second xdag field.

And 4bits can only represents 16 types. That's why just handle 16 types in code.

**Comment by sgaragagghu** [comment]
Good. 
But you can also do:
case XDAG_FIELD_RESERVE0:
 			case XDAG_FIELD_RESERVE1:
 			case XDAG_FIELD_RESERVE2:
 			case XDAG_FIELD_RESERVE3:
 			case XDAG_FIELD_RESERVE4:
 			case XDAG_FIELD_RESERVE5:
 			case XDAG_FIELD_RESERVE6:
				break;

**Comment by sgaragagghu** [comment]
it will let everyone to do a network hard fork, my bad that i didn't think about that first time i saw this PR

**Pull request merged**
