### PR TITLE
When tmpfile is full a new one will be created

### PR DESCRIPTION
**Pull request by sgaragagghu**

### CODE REVIEW

**Comment by sgaragagghu** [comment]
Need to free up the memory

**Comment by xrdavies** [comment]
@sgaragagghu Sorry, I'm not quite sure about what is the issue for this PR. Could you explain it?

**Comment by sgaragagghu** [comment]
tmp file size is finite (around 34gb), when the file is full the pool crash. This change will create a new file when the tmp file is full.

**Comment by xrdavies** [comment]
@sgaragagghu Okay. It depends on the sysconf of virtual memory. sysconf issue again.

**Comment by sgaragagghu** [comment]
@xrdavies It isn't sysconf.
File size is setted at the beginning as you can see here #327.
`if (xdag_mem_init(g_light_mode && !miner_address ? 0 : (((get_timestamp() - XDAG_ERA) >> 10) + (uint64_t)365 * 24 * 60 * 60) * 2 * sizeof(struct block_internal))) {
`
File size is setted and fixed at the beginning, just because it need to "reserve" *contiguous* heap space. 

You can simply set the file bigger as #327 but before of after it will be filled up, but in #319 it will never fail for tmp file full because it just create a new file when it is full.

**Comment by xrdavies** [comment]
@sgaragagghu  Okay, it's not the issue I thought.

**Pull request merged**
